const ActionTypes = {
    PROFILE: "PROFILE",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    MENU: "MENU",
    NAV_PATH: "NAV_PATH",
    VOTER_LIST: "VOTER_LIST",
    VOTER_DETAIL: "VOTER_DETAIL",
    VEND_LIST: "VEND_LIST",
    VEND_DETAIL: "VEND_DETAIL",
    CONTACT_LIST: "CONTACT_LIST",
    CONTACT_DETAIL: "CONTACT_DETAIL",
    DASHBOARD: "DASHBOARD",
    ALERT_MSG: "ALERT_MSG"
};

const MenuAction = {
    MINI_SIDENAV: "MINI_SIDENAV",
    TRANSPARENT_NAVBAR: "TRANSPARENT_NAVBAR",
    FIXED_NAVBAR: "FIXED_NAVBAR",
    LAYOUT: "LAYOUT",
};

export { ActionTypes, MenuAction };